Map<int, String> episodesSeasons = {
  1: 'Season 1, Episode 1',
  2: 'Season 1, Episode 2',
  3: 'Season 1, Episode 3',
  4: 'Season 1, Episode 4',
  5: 'Season 1, Episode 5',
  6: 'Season 1, Episode 6',
  7: 'Season 1, Episode 7',
  8: 'Season 1, Episode 8',
  9: 'Season 1, Episode 9',
  10: 'Season 1, Episode 10',
  11: 'Season 1, Episode 11',
  12: 'Season 2, Episode 1',
  13: 'Season 2, Episode 2',
  14: 'Season 2, Episode 3',
  15: 'Season 2, Episode 4',
  16: 'Season 2, Episode 5',
  17: 'Season 2, Episode 6',
  18: 'Season 2, Episode 7',
  19: 'Season 2, Episode 8',
  20: 'Season 2, Episode 9',
  21: 'Season 2, Episode 10',
  22: 'Season 3, Episode 1',
  23: 'Season 3, Episode 2',
  24: 'Season 3, Episode 3',
  25: 'Season 3, Episode 4',
  26: 'Season 3, Episode 5',
  27: 'Season 3, Episode 6',
  28: 'Season 3, Episode 7',
  29: 'Season 3, Episode 8',
  30: 'Season 3, Episode 9',
  31: 'Season 3, Episode 10',
  32: 'Season 4, Episode 1',
  33: 'Season 4, Episode 2',
  34: 'Season 4, Episode 3',
  35: 'Season 4, Episode 4',
  36: 'Season 4, Episode 5',
  37: 'Season 4, Episode 6',
  38: 'Season 4, Episode 7',
  39: 'Season 4, Episode 8',
  40: 'Season 4, Episode 9',
  41: 'Season 4, Episode 10',
  42: 'Season 5, Episode 1',
  43: 'Season 5, Episode 2',
  44: 'Season 5, Episode 3',
  45: 'Season 5, Episode 4',
  46: 'Season 5, Episode 5',
  47: 'Season 5, Episode 6',
  48: 'Season 5, Episode 7',
  49: 'Season 5, Episode 8',
  50: 'Season 5, Episode 9',
  51: 'Season 5, Episode 10',
};

final Map<int, String> episodesSinopsis = {
  1: 'Rick takes Morty on a trip to another dimension to find seeds for "mega-trees," while Jerry and Beth argue over Rick\'s influence on their son.',
  2: 'Rick creates a device to make family dog Snuffles smarter, but it goes poorly. Rick and Morty invade the dreams of Morty\'s math teacher.',
  3: 'Morty ends up at a bizarre theme park of infectious diseases located inside of a homeless man. Jerry\'s parents introduce their new mutual lover.',
  4: 'Aliens send Rick, Morty and Jerry into an alternate reality, and Rick tries to get them out as oblivious Jerry pitches a marketing slogan for apples.',
  5: 'Morty has grown weary of Rick\'s shenanigans, so he leads a supposedly safer adventure. Jerry conjures weird creatures to help him with his golf game.',
  6: 'A potion designed to make Morty attractive to one girl goes viral and infects all of Earth, so Rick has to clean up the mess by creating another mess.',
  7: 'After Morty fathers a child with a sex robot, Rick and Summer visit the robot\'s planet, where the kid grows into an adult within days.',
  8: 'Unimpressed with what\'s on TV, Rick installs cable that gets shows from other dimensions. Everyone uses special goggles to see their alternate selves.',
  9: 'Rick is skeptical of Summer\'s new job at a shop run by the devil. Jerry and Morty argue about Pluto\'s status as a planet and end up traveling there.',
  10: 'Rick\'s just trying to enjoy a nice breakfast, but he\'s kidnapped by a group of alternate Ricks and taken to stand trial for crimes against Ricks.',
  11: 'When Jerry and Beth go away to take part in a re-creation of the sinking of the Titanic, Rick and Summer throw a party that gets out of control.',
  12: 'Rick unfreezes time, but since he, Morty and Summer have been living for so long on frozen time, a parallel dimension develops.',
  13: 'After Rick sells a gun to an alien assassin so he can afford an afternoon at a video arcade, Morty tries to stop the assassin.',
  14: 'Rick, Morty and Summer stumble on a hive mind named Unity that Rick used to date. Summer objects to Unity\'s control over an alien planet\'s population.',
  15: 'The family battles a parasite that implants fake memories into their heads, which leads them to wonder if any of them are real.',
  16: 'When an alien entity appears with musical demands, Rick and Morty call on Ice-T to help them write a tune for an intergalactic song competition.',
  17: 'When Rick\'s car breaks down, he and Morty go inside its battery. Morty discovers that Rick has created a miniature universe inside the battery.',
  18: 'Summer asks Rick to transport his mind into a teenager to shield her from vampires at school. Beth and Jerry go to "off-planet" marriage counseling.',
  19: 'Jerry is rushed to an alien hospital when he eats ice cream Rick was using to develop a dangerous bacteria. Rick rigs the hospital cable box.',
  20: 'Rick and Morty land on a planet where all the citizens are allowed to commit crimes -- including murder -- without punishment for one night.',
  21: 'When Jerry accidentally gets transported to the planet hosting Birdperson and Tammy\'s wedding, the whole family attends the ill-fated ceremony.',
  22: 'Summer and Morty travel interdimensionally to locate Rick and find a bunch of Ricks. Rick craves a very specific chicken nugget dipping sauce.',
  23: 'With things in turmoil at home, Rick, Morty and Summer travel to a post-apocalyptic world to (rather violently) work out some personal issues.',
  24: 'Rick turns himself into a pickle while the rest of the family goes to therapy. Now Rick has to figure out how to stop being a pickle.',
  25: 'While ostensibly helping a group of superheroes called the Vindicators, Rick instead drunkenly sets up a "Saw"-like scenario for them to navigate.',
  26: 'Rick and Jerry go to a resort where dying is impossible, but a creature wants to kill Rick anyway. Summer\'s attempt to enlarge her breasts goes awry.',
  27: 'After another exhausting adventure, Rick and Morty decide they need a vacation. But things go a little haywire when they try a special detox machine.',
  28: 'Rick and Morty encounter a visiting Rick and Morty from the Citadel of Ricks before heading off on an amazing adventure to Atlantis.',
  29: 'Rick shows Morty a room filled with memories Morty begged him to remove from his mind, and things go off the rails when Rick starts restoring them.',
  30: 'Rick and Beth sort out issues from her childhood by visiting a world called Froopyland. Morty and Summer are a little wary of Jerry\'s new girlfriend.',
  31: 'The president needs help from Rick and Morty, prompting a bit of a confrontation. Beth begins to suspect that she may be a clone.',
  32: 'After family breakfast, Rick asks Morty to accompany him to Forbodulon Prime to get some "death crystals," and Morty doesn\'t handle them well.',
  33: 'Jerry develops an app at the request of a persistent alien with a "Do Not Develop My App" forehead tattoo. A determined Rick tracks a mystery pooper.',
  34: 'Rick assembles a crew to break into a heist convention, then needs another crew to stop a heist-planning robot. And Morty writes a heist script.',
  35: 'Rick reluctantly gives in to Morty\'s wishes to get a pet dragon, then things get weird. Jerry befriends a talking cat and they go to Florida.',
  36: 'Rick and Morty get caught up in a full-on snake war after a space snake bites Morty. Jerry tries to prove he can hang Christmas lights without dying.',
  37: 'Rick and Morty get caught in a continuity-creating anthology device full of people telling stories about Rick.',
  38: 'Face-sucking aliens cause issues for Morty and Rick, especially when after returning home they realize they left Summer behind in the aliens\' world.',
  39: 'Morty challenges Rick to build him the real-life equivalent of a "save game" function to live without consequence. Also, there\'s a giant vat of acid.',
  40: 'Jerry\'s plan to take the whole family on a camping trip is sidetracked when Rick gets news that he may have impregnated a planet.',
  41: 'Two Beths, a corporate-sponsored planet incinerator and some faces from the past force Rick and family to "do a Star Wars" to save Earth.',
  42: 'It\'s a busy night at the Smith house as Rick\'s nemesis pays a visit and Morty invites a girl over. Then some stuff happens with a portal in the garage.',
  43: 'Killer squids are after the Smiths, but luckily Rick created a decoy family. Or are they real? Can the decoys make decoys? Who\'s real? Are you real?',
  44: 'Morty falls head-over-heels in love with an ecological superhero, leaving Summer to join Rick on a bender of interplanetary apocalyptic hedonism.',
  45: 'The Smiths band together to fight an army of giant mutant sperm, and let\'s just say everyone would be better off if Morty stays away from Beth\'s work.',
  46: 'Beth crashes Rick and Jerry\'s hellish guys night out, while Morty and Summer attempt to use a spaceship to impress a cool new kid at school.',
  47: 'Rick turns himself into a turkey after he ruffles the President\'s feathers on Thanksgiving, and the situation soon spirals into total clucking carnage.',
  48: 'The Smiths get a lesson on the meaning of family after Rick cancels a trip to Boob World to acquire the fifth and final GoTron ferret.',
  49: 'With the rest of the family out of town on a cruise, Rick is left to his own devices at home and decides it\'s time to reconnect with an old friend.',
  50: 'When Rick starts using birds as sidekicks, Morty finds a new partner in a portal. Is Rick and Morty\'s interdimensional partnership done forever?',
  51: 'Rick\'s still doing the crows thing, but a middle-aged Morty hopes to reconnect with Rick, leading them down an emotional path in a familiar location.'
};

final Map<int, String> episodesImages = {
  1: 'assets/episodes/episode_1.png',
  2: 'assets/episodes/episode_2.png',
  3: 'assets/episodes/episode_3.png',
  4: 'assets/episodes/episode_4.png',
  5: 'assets/episodes/episode_5.png',
  6: 'assets/episodes/episode_6.png',
  7: 'assets/episodes/episode_7.png',
  8: 'assets/episodes/episode_8.png',
  9: 'assets/episodes/episode_9.png',
  10: 'assets/episodes/episode_10.png',
  11: 'assets/episodes/episode_11.png',
  12: 'assets/episodes/episode_12.png',
  13: 'assets/episodes/episode_13.png',
  14: 'assets/episodes/episode_14.png',
  15: 'assets/episodes/episode_15.png',
  16: 'assets/episodes/episode_16.png',
  17: 'assets/episodes/episode_17.png',
  18: 'assets/episodes/episode_18.png',
  19: 'assets/episodes/episode_19.png',
  20: 'assets/episodes/episode_20.png',
  21: 'assets/episodes/episode_21.png',
  22: 'assets/episodes/episode_22.png',
  23: 'assets/episodes/episode_23.png',
  24: 'assets/episodes/episode_24.png',
  25: 'assets/episodes/episode_25.png',
  26: 'assets/episodes/episode_26.png',
  27: 'assets/episodes/episode_27.png',
  28: 'assets/episodes/episode_28.png',
  29: 'assets/episodes/episode_29.png',
  30: 'assets/episodes/episode_30.png',
  31: 'assets/episodes/episode_31.png',
  32: 'assets/episodes/episode_32.png',
  33: 'assets/episodes/episode_33.png',
  34: 'assets/episodes/episode_34.png',
  35: 'assets/episodes/episode_35.png',
  36: 'assets/episodes/episode_36.png',
  37: 'assets/episodes/episode_37.png',
  38: 'assets/episodes/episode_38.png',
  39: 'assets/episodes/episode_39.png',
  40: 'assets/episodes/episode_40.png',
  41: 'assets/episodes/episode_41.png',
  42: 'assets/episodes/episode_42.png',
  43: 'assets/episodes/episode_43.png',
  44: 'assets/episodes/episode_44.png',
  45: 'assets/episodes/episode_45.png',
  46: 'assets/episodes/episode_46.png',
  47: 'assets/episodes/episode_47.png',
  48: 'assets/episodes/episode_48.png',
  49: 'assets/episodes/episode_49.png',
  50: 'assets/episodes/episode_50.png',
  51: 'assets/episodes/episode_51.png'
};
